<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_more_vert</name>
   <tag></tag>
   <elementGuidId>bd79c053-a01e-491c-8841-05b3cdc17113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-tooltip-trigger.mat-menu-trigger.options.custom-button.z-index-up__cdk.mat-icon-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0530910a-eade-4004-9cd9-b484506e5b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>75451ae0-6810-484d-a1b2-9a86c1085527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltipposition</name>
      <type>Main</type>
      <value>below</value>
      <webElementGuid>9919d845-535f-4d0e-a3d5-156bdfceaf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>bb27f7fa-3ec3-4384-86a9-bc00310c5432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Opciones</value>
      <webElementGuid>0c7f4468-fb88-4d00-9502-2d756aca1070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>c1c5f623-4179-4124-b7b2-5af6ab03dc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mis-materias&quot;)/div[@class=&quot;d-flex materia-container ng-star-inserted&quot;]/div[@class=&quot;materia d-flex flex-column justify-content-between route-animations-elements verdeCN ng-star-inserted&quot;]/div[@class=&quot;card-inner flipped&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator card-back custom-bg__dark d-flex flex-column px-0 pb-2 pt-0&quot;]/div[@class=&quot;card-back__container&quot;]/div[@class=&quot;libros py-1 custom-border__regular d-flex justify-content-between align-items-center w-100 ng-star-inserted&quot;]/div[@class=&quot;actions-menu z-index-up__cdk&quot;]/button[@class=&quot;mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>e03f1d8c-a002-4d3a-867d-b7ca87090f11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>64d4a555-9b1e-4ab3-9e80-3fde287c9dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[2]/following::button[2]</value>
      <webElementGuid>b73de21f-76e2-478f-a7a9-33694183d375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[1]/following::button[2]</value>
      <webElementGuid>868b9911-5913-4a3d-9ff2-a470f669d1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[3]/preceding::button[1]</value>
      <webElementGuid>33da1636-c243-4ce2-8515-d25b9356731d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[4]/preceding::button[1]</value>
      <webElementGuid>790788ec-764e-4a36-9167-97c9caac7b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>508d164d-829d-4c4c-adc8-7d16d3cd2e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>ec157b16-aece-4481-8d11-c6213fc5c7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libro_Profesor_estres_1'])[1]/following::button[1]</value>
      <webElementGuid>964cbf92-ac27-417d-85bf-3227d86bee13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
