<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aceptar_80</name>
   <tag></tag>
   <elementGuidId>ae74afb3-da52-451c-933a-4e9f57addbaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.default-button.default-button__primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02fb602f-b983-4cca-b518-b02d208a3b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e9f3639-d61b-4b22-a760-1a0ac6a45371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7b77ac79-5a6a-493e-bd96-664e26170996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default-button default-button__primary</value>
      <webElementGuid>ba219a3c-e80f-4dac-8b89-5afe2e28429d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>e5a49682-25a6-4011-b90d-b2328ab42574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-reasignar-grupo&quot;)/div[@class=&quot;mat-dialog-actions justify-content-start mt-2 mb-0 pb-0&quot;]/button[@class=&quot;default-button default-button__primary&quot;]</value>
      <webElementGuid>b8cb1d2d-2875-4b0d-a02e-e09f68d5a9d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>760d33fe-e00b-49c7-a5c8-e12fc9ca993a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-reasignar-grupo']/div[3]/button[2]</value>
      <webElementGuid>3f9a5c92-e027-45c0-91df-3407df41994e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/following::button[1]</value>
      <webElementGuid>f67f8923-7633-4d1e-a11a-7c76ce0103db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignación'])[1]/following::button[2]</value>
      <webElementGuid>3dd13e56-2408-492e-9f94-a366ea2455c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>d31cc08f-d8f1-4deb-89e5-1d15e06c5b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>caa3913d-8235-4ff3-8042-685a98d1b5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aula-planeta-reasignar-grupo/div/div[3]/button[2]</value>
      <webElementGuid>538f84bd-bee9-49fe-ad78-b8ad6a3930b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>e9a46bf9-6ed8-4a1c-9577-b8c7ecc27fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
