<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Entrar</name>
   <tag></tag>
   <elementGuidId>da96db61-1c51-475a-8333-5c32c2eed14d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.w-100.default-button.default-button__secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b87e252b-f12a-4e5b-aec8-d35f8068224d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1afb6d9-d888-4f7b-93af-48b71dd335c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bd412017-d2bf-431d-881f-81c547e0cba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 default-button default-button__secondary</value>
      <webElementGuid>095992f9-cc06-407c-b353-e89ccc886389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entrar</value>
      <webElementGuid>83a923b8-4a05-4ae4-ad48-b7f34d46b9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/aula-planeta-root[@class=&quot;ng-tns-c231-0&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;default-theme login-page ng-star-inserted&quot;]/div[@class=&quot;data-container d-flex flex-column justify-content-start justify-content-sm-center&quot;]/div[@class=&quot;login-container d-flex flex-row&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/form[@class=&quot;d-flex flex-column ng-dirty ng-touched ng-valid&quot;]/fieldset[@class=&quot;d-flex flex-column mb-4&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;w-100 default-button default-button__secondary&quot;]</value>
      <webElementGuid>ac202922-0eab-4243-a306-0ee11eb2b61a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>d6e3501d-46ff-4ee7-8e84-af898c8c67e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear cuenta'])[1]/following::button[1]</value>
      <webElementGuid>62c209f8-41e7-4a50-a296-550781a5d661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Has olvidado tu contraseña?'])[1]/following::button[2]</value>
      <webElementGuid>c23141d7-c3da-4ed0-870c-ffa7467306e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar sesión'])[2]/preceding::button[1]</value>
      <webElementGuid>bf34bc43-f464-460c-94aa-441ae5405ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar con Office 365'])[1]/preceding::button[1]</value>
      <webElementGuid>3578d610-a8db-43ec-bab5-cb01fa73ddb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrar']/parent::*</value>
      <webElementGuid>ae821fc3-765f-441c-8538-4e2a12b8e194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>6d43b1fc-29c7-4e30-a3e4-981790550f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Entrar' or . = 'Entrar')]</value>
      <webElementGuid>cfd2af6e-119f-44cd-88c7-3290893f6faa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
