<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clases  Asignacin 5 PRI A5 PRI B5 PRI C_4850c7</name>
   <tag></tag>
   <elementGuidId>07ae86e0-0252-4f86-a7fa-12ada2f2b56a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-dialog-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dialog-reasignar-grupo']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93e3923a-5a8a-445f-93ef-4723028bad85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-content</value>
      <webElementGuid>4b532e44-703a-4456-bd03-1fa9624dea6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E </value>
      <webElementGuid>00bda729-2a47-466a-ad73-7a3966102071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-reasignar-grupo&quot;)/div[@class=&quot;mat-dialog-content&quot;]</value>
      <webElementGuid>e2226f3e-b933-4e8b-a649-ca0a01bb266e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-reasignar-grupo']/div[2]</value>
      <webElementGuid>fec50487-2c26-48ad-af84-bca7f4a080ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libro_Profesor_estres_1'])[1]/following::div[1]</value>
      <webElementGuid>9dbea0cf-f4f9-4a54-9dac-7961cb88e51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignar grupos'])[1]/following::div[2]</value>
      <webElementGuid>c7fc9001-1b43-4a90-99e1-1bcc16f58705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aula-planeta-reasignar-grupo/div/div[2]</value>
      <webElementGuid>41a9e7df-a4f7-4fa3-b965-9027b7b569fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E ' or . = ' Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E ')]</value>
      <webElementGuid>6500d5a9-f9b8-4691-b1e9-0197f34de0e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
