<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_form-control ng-untouched n_eceae4 (1)</name>
   <tag></tag>
   <elementGuidId>bcb55cd5-a9d2-4437-92a7-92b62ae8453d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d26b0d9-b46a-4713-aa22-01b2722d09a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>51757268-38f2-4996-ac51-3917f055af84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>bd25a059-947f-4c7c-b27f-c7c6cc0b0f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b761f31f-e7f5-40dd-84c2-736cb9aa9c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>2f6c3b03-a875-491c-a837-3530e76c192c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/aula-planeta-root[@class=&quot;ng-tns-c231-0&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;default-theme login-page ng-star-inserted&quot;]/div[@class=&quot;data-container d-flex flex-column justify-content-start justify-content-sm-center&quot;]/div[@class=&quot;login-container d-flex flex-row&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/form[@class=&quot;d-flex flex-column ng-untouched ng-invalid ng-dirty&quot;]/fieldset[@class=&quot;d-flex flex-column mb-4&quot;]/div[@class=&quot;form-group w-100 default-input position-relative text-left&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>645f3e94-c879-4624-b79e-a264122d3d91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>a0eb25fc-e938-4313-b16a-0975b8a447d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1e2f3ef0-0047-4d6b-914b-da632f0cabcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Contraseña']</value>
      <webElementGuid>a47fa232-64a9-4d34-a817-9881e1334622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
