<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-checkbox_</name>
   <tag></tag>
   <elementGuidId>ae1e1ad7-7b27-4f49-9f94-5a6a45becb76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-checkbox-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='mat-checkbox-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-checkbox</value>
      <webElementGuid>40b6c486-c67e-4de5-b041-b03e40bf3e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox mat-accent mat-checkbox-checked</value>
      <webElementGuid>9264dc24-4efe-4344-a45b-5caac4cf7a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-checkbox-2</value>
      <webElementGuid>fec253e9-a8df-4b3a-b9a0-5d48e7a32963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>b3d3a69b-cc12-4c44-a119-5737e73ddab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-checkbox-2&quot;)</value>
      <webElementGuid>a13361cd-e60a-42b6-b8ca-4b3894c94e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-checkbox-2']</value>
      <webElementGuid>13835742-188e-4998-8887-48ebf3fb6825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-reasignar-grupo']/div[2]/table/tbody/tr[2]/td[2]/mat-checkbox</value>
      <webElementGuid>dfd305eb-36d5-4665-a349-cd2fb2053402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignación'])[1]/following::mat-checkbox[2]</value>
      <webElementGuid>4057b520-4610-4f35-94b4-065cb61841c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clases'])[1]/following::mat-checkbox[2]</value>
      <webElementGuid>5fffe73e-3cbc-4b2c-8726-8bf5633a7aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/preceding::mat-checkbox[4]</value>
      <webElementGuid>d309c00a-1eec-4afa-9d9c-9b0fc0d83671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[2]/preceding::mat-checkbox[4]</value>
      <webElementGuid>0a938a39-cfa6-48c0-9136-faf2cc855e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/mat-checkbox</value>
      <webElementGuid>f71f01b3-2cb7-4f31-bc2c-e8995be34173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-checkbox[@id = 'mat-checkbox-2' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>346b11a3-7511-4734-9016-83d738bf9895</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
