<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Asignar grupos_PopUp</name>
   <tag></tag>
   <elementGuidId>a4bd1edf-0932-4089-ac48-d95ef8ff23ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>196f1220-4e69-44fc-bb55-5a52424ac84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a734ae3f-ec13-40bf-a61c-513bd160df5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dcee1f2f-ba1c-45cf-bcf9-8e58795c98dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c113-18 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>9c940067-6d9c-4fa2-b93d-5a105ce2aa32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-0</value>
      <webElementGuid>309a4b72-6cec-4811-91ed-cd17663cb7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>5fbd53cc-9016-4214-b62f-8bc9bad7d8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-0</value>
      <webElementGuid>c58c6b3f-f2be-4da7-9f49-5ae7d13f1ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar</value>
      <webElementGuid>38c8ef30-536d-407a-ba6c-431dc57f7c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)</value>
      <webElementGuid>f207135f-8197-4b89-bae6-b13ed6b91443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      <webElementGuid>b968117b-d2b5-489e-b533-6ce13112c790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/mat-dialog-container</value>
      <webElementGuid>a67dc80f-2cb2-4f63-8640-a552b9812da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conoce el entorno de aprendizaje'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>9346a63d-3421-4a24-8dc3-a2a4705e5d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumnado'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>1b84d7a7-b5d8-4293-9a3f-c8f45e984d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>08bcb377-ed1c-4772-8c0d-65a8533b9bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar' or . = 'Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar')]</value>
      <webElementGuid>150ed85c-c358-4a6d-85e3-f657326f4e2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
