<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Asignar gruposSeleccio_88e51b</name>
   <tag></tag>
   <elementGuidId>cdb80e97-b1e0-4d36-b51f-963a6383b298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>ab609459-0606-4dc3-a45e-920654c0bce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aeef5d68-9d06-4b29-be37-abaa0b331dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3fa6e386-df60-4022-992f-42b43cbd79ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c113-17 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>a38f11d5-6886-48e0-93cb-fdc4cd723e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-0</value>
      <webElementGuid>0ab4c132-1960-401d-acca-16fad63f556d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>1a80a273-ebee-4657-acbc-7ae698c516f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-0</value>
      <webElementGuid>c3471155-9c14-48f7-9c35-4956acd477a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar</value>
      <webElementGuid>7df75fc8-96b8-42c2-81a2-d2630f24f9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)</value>
      <webElementGuid>8a099b5a-f64a-4ef3-839b-84146bcb606d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      <webElementGuid>5cf401f2-9d65-4d82-aaed-47ad11f288a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/mat-dialog-container</value>
      <webElementGuid>68c4d98b-ed24-48ea-8b07-f9c5c47fadb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conoce el entorno de aprendizaje'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>0c2c92f2-9ad8-4f19-bace-524cb4387e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumnado'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>e98ed67e-2731-4dd3-ba2a-b13224ee553c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>57492576-1a7a-40ea-b71b-be96721a763a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar' or . = 'Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar')]</value>
      <webElementGuid>bd45e575-ea15-40ba-af7d-4f2dd553e7a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
