<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_search (1)</name>
   <tag></tag>
   <elementGuidId>8179e702-0b37-4101-8405-d4657052aced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div/div/div/a[5]/div/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mat-list-item.mat-focus-indicator.mat-tooltip-trigger.ng-tns-c228-1.ng-star-inserted.cdk-focused.cdk-mouse-focused > div.mat-list-item-content > mat-icon.mat-icon.notranslate.material-icons-round.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>8493d987-0b93-4300-b5b7-78380246207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d113baa0-25bc-4f25-8c10-2e93932f6044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2d5efbb2-5d2d-41e3-a648-1a2287aac17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons-round mat-icon-no-color</value>
      <webElementGuid>99a9010a-df9a-4fc2-8d35-c2d85bff8387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>31764d0c-cb3c-477e-b2fd-ad9b9efc7de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>cb62887c-8d11-45e8-a7fe-bfa08d6b3cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;content ng-tns-c228-1 ng-trigger ng-trigger-routeAnimations&quot;]/div[@class=&quot;menu-column position-fixed d-flex flex-column align-items-center ng-tns-c228-1 ng-star-inserted&quot;]/div[@class=&quot;primaryMenu ng-tns-c228-1&quot;]/a[@class=&quot;mat-list-item mat-focus-indicator mat-tooltip-trigger ng-tns-c228-1 ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;mat-list-item-content&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons-round mat-icon-no-color&quot;]</value>
      <webElementGuid>c41eb0ad-000c-4897-941b-b590685382a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/div/div/a[5]/div/mat-icon</value>
      <webElementGuid>230db1db-0097-4e96-8f11-0d8415b438d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='people'])[2]/following::mat-icon[1]</value>
      <webElementGuid>455572ac-b78a-424c-8e42-e25106a6f141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='assignment_ind'])[2]/following::mat-icon[2]</value>
      <webElementGuid>6ec05139-2d71-481b-b175-4fa857a07abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='widgets'])[2]/preceding::mat-icon[1]</value>
      <webElementGuid>fddf750d-2700-40ef-813a-0a23f2766f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='work'])[2]/preceding::mat-icon[2]</value>
      <webElementGuid>8e29c9c3-5d03-425f-9e94-2843fb70b52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/div/mat-icon</value>
      <webElementGuid>b5e54899-6779-423c-9333-63f8c819b528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'search' or . = 'search')]</value>
      <webElementGuid>07ede830-c670-4ab8-80eb-65aa938a8ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
