<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_Bsqueda_ng-star-inserted (1)</name>
   <tag></tag>
   <elementGuidId>1e1919d2-7323-4c07-96cb-494847fe3ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>circle.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>7a7d02e3-42fa-4411-8164-5a60ea743a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>aaedf565-30e6-4d15-a7e8-480caf23ffda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>ebc64260-7553-410c-a650-5e81aa1aa697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>7.5</value>
      <webElementGuid>7d3447c7-1884-482a-a69c-a20f462cd5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>6e9fde57-8559-4f3d-9278-6cc20ad162be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buscador&quot;)/div[@class=&quot;mt-4 ng-tns-c379-18&quot;]/div[@class=&quot;expansible-jumbotron expansible-jumbotron__grey ng-tns-c379-18&quot;]/div[@class=&quot;d-flex flex-column mb-0 w-100 filter-input ng-tns-c379-18&quot;]/div[@class=&quot;d-flex mb-0 py-2 w-100 align-items-center justify-content-between ng-tns-c379-18&quot;]/mat-card-subtitle[@class=&quot;mat-card-subtitle custom-text font-weight-bold mb-0 pt-0 w-100 ng-tns-c379-18&quot;]/div[@class=&quot;d-flex pt-0 mb-2 ng-tns-c379-18&quot;]/div[@class=&quot;search-filter-input d-flex align-items-center px-1 ng-tns-c379-18 search-filter-input__typing&quot;]/mat-spinner[@class=&quot;mat-spinner mat-progress-spinner ml-2 custom-spinner mat-primary ng-tns-c379-18 mat-progress-spinner-indeterminate-animation ng-star-inserted&quot;]/svg[1]/circle[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>33a3c4ad-c46f-4a0f-a1a6-d4d136416c1d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
