<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_Bsqueda_ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>8489c3c7-3b52-4e0c-b1f7-503d102c5cca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>circle.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>fbf6ab57-9b42-4818-8cde-48c793517d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>bda171f9-15dc-4122-b6a8-bcd1f4c60a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>00ceee76-e08f-4c7e-b4aa-f7347cc0bf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>7.5</value>
      <webElementGuid>8fa2b963-6082-4b5e-9c07-ed48b02b0750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>904a3c29-81b1-43b0-a018-0ce2bc7506a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buscador&quot;)/div[@class=&quot;mt-4 ng-tns-c344-18&quot;]/div[@class=&quot;expansible-jumbotron expansible-jumbotron__grey ng-tns-c344-18&quot;]/div[@class=&quot;d-flex flex-column mb-0 w-100 filter-input ng-tns-c344-18&quot;]/div[@class=&quot;d-flex mb-0 py-2 w-100 align-items-center justify-content-between ng-tns-c344-18&quot;]/mat-card-subtitle[@class=&quot;mat-card-subtitle custom-text font-weight-bold mb-0 pt-0 w-100 ng-tns-c344-18&quot;]/div[@class=&quot;d-flex pt-0 mb-2 ng-tns-c344-18&quot;]/div[@class=&quot;search-filter-input d-flex align-items-center px-1 ng-tns-c344-18 search-filter-input__typing&quot;]/mat-spinner[@class=&quot;mat-spinner mat-progress-spinner ml-2 custom-spinner mat-primary ng-tns-c344-18 mat-progress-spinner-indeterminate-animation ng-star-inserted&quot;]/svg[1]/circle[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>b49edf91-dd28-4170-bbda-287870404fde</webElementGuid>
   </webElementProperties>
</WebElementEntity>
