<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>576ff633-d1c9-4e3b-bba3-76af6397ece6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/div[@id='roundbutton_14']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ed3488cc-0baa-4b69-a976-b098ddb4511d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
