<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_buttonPantalla_Esquema2</name>
   <tag></tag>
   <elementGuidId>94592272-9fc0-425e-a08c-2b58eb01a64f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pantalla_10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#material</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1813c59e-8ebc-4319-8087-cd4196e4163b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>material</value>
      <webElementGuid>32e70bed-0cc8-427d-a9f2-0b818b99a0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c319-45</value>
      <webElementGuid>a5abb619-1852-4df4-9089-90d934646f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat.aulaplaneta.com/Contenido/TemplatesCPCA/html5/v1/players/F1/Principal.html?_preload_data=/Contenido/Modulos/1-2110-1-27734/</value>
      <webElementGuid>efeac1e7-d63f-4d7f-919f-df0e5947dad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;material&quot;)</value>
      <webElementGuid>4d55293c-ef41-4427-abde-99364e028261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pantalla_10']</value>
      <webElementGuid>c799b63b-a8b3-45d1-a447-029ee6c56cc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
