<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_buttonRoundButton_Esquemadelcilcodelagua</name>
   <tag></tag>
   <elementGuidId>94b6c80d-58d2-4fb2-81ea-8145b41e5f45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='roundbutton_16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#image_30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8774c2f-7c98-4dc6-88e6-74df76f4fccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image_30</value>
      <webElementGuid>6b4e3a61-8a05-4342-8cb6-51ffe8ccb747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uiobject uiimage</value>
      <webElementGuid>c2f5cf66-eced-4db4-a750-282163b87076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image_30&quot;)</value>
      <webElementGuid>e686db29-c875-4684-907d-dd348d69a00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mis materias - aulaPlaneta/div_buttonPantalla_verciclodelagua</value>
      <webElementGuid>ac6fcf7a-6c6a-4f94-82b3-06bb3202614b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='roundbutton_16']</value>
      <webElementGuid>25506dd3-0191-46b1-ade8-3917cfc4e853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
