<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ver ciclo del agua</name>
   <tag></tag>
   <elementGuidId>0ca614df-6c7d-4af3-8784-72af30ce07e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='realContent'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#roundbutton_14 > #textButtonContainer > tbody > tr > td > #realContent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>68eb9d11-e6fd-43af-a612-587edd9a600d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>realContent</value>
      <webElementGuid>ef81a0a9-f653-4e7a-9668-1e31ac95df41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver ciclo del agua</value>
      <webElementGuid>a8906352-45e6-4202-83a5-4c2e2f0e75ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roundbutton_14&quot;)/table[@id=&quot;textButtonContainer&quot;]/tbody[1]/tr[1]/td[1]/div[@id=&quot;realContent&quot;]</value>
      <webElementGuid>902bfc04-e951-4275-8d69-bf596257c354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mis materias - aulaPlaneta/iframe_Presentacin multimedia_material</value>
      <webElementGuid>c47a4908-2b6f-4e55-84cf-d920c3e666e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='realContent'])[5]</value>
      <webElementGuid>b53a9729-52d3-4405-a40c-fc2bf608d2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='textButtonContainer']/tbody/tr/td/div)[5]</value>
      <webElementGuid>57c68de6-1a69-48c9-b83d-b6c172f51d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtración'])[1]/following::div[2]</value>
      <webElementGuid>9be447e2-4b72-408e-9f4b-ed31537e71bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Precipitación'])[1]/following::div[4]</value>
      <webElementGuid>2c0df8c1-b879-42a0-a99d-7e457fb185f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esquema del ciclo del agua'])[1]/preceding::div[1]</value>
      <webElementGuid>5c96f8bf-e2d3-4815-8391-92e2a5c98ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando...'])[1]/preceding::div[7]</value>
      <webElementGuid>1e62cf84-77ec-406a-9a70-d8930153fa6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver ciclo del agua']/parent::*</value>
      <webElementGuid>47e72fc0-710e-4a7e-b345-c491e1f083a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr/td/div</value>
      <webElementGuid>cdb373bc-4d8b-42d5-8e51-64423db66acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'realContent' and (text() = 'Ver ciclo del agua' or . = 'Ver ciclo del agua')]</value>
      <webElementGuid>879421db-c7e8-484e-913c-a00cc7637edb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
