<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_buttonRoundButton_Esquemadelcilcodelagua - Copy</name>
   <tag></tag>
   <elementGuidId>4185f32a-40e8-4798-80bc-44529f6da93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div[2]/div[1]/div[1]/div[6]/table/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#image_30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26bb6a65-62fb-4ee4-9bc4-1774a1bbd32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image_30</value>
      <webElementGuid>042b06a8-55eb-4631-b539-db129634d527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uiobject uiimage</value>
      <webElementGuid>1b18d619-596c-45ee-9ad9-d8bf0a06aaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image_30&quot;)</value>
      <webElementGuid>133cf5c9-8295-4632-b2e7-2bf7d0199bf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/div[2]/div[1]/div[1]/div[6]/table/tbody/tr/td/div</value>
      <webElementGuid>28797fe8-4dde-4cc3-a987-2bcef6dc20a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
