<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_buttonRoundButton_Esquemadelcilcodelagua</name>
   <tag></tag>
   <elementGuidId>94b6c80d-58d2-4fb2-81ea-8145b41e5f45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='roundbutton_16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#image_30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbbc8df1-3497-421e-916f-d144c7d51841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image_30</value>
      <webElementGuid>7d5f59e6-6ed9-4ca0-bd1f-e36c5970174a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uiobject uiimage</value>
      <webElementGuid>80d72b1c-5269-4394-b72c-afcd405a7095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image_30&quot;)</value>
      <webElementGuid>3f94ce97-1b5f-46d4-80a8-4cf6a285b98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mis materias - aulaPlaneta/div_buttonPantalla_Esquema2</value>
      <webElementGuid>e721a903-6345-4b27-9094-342c71b4cc3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='roundbutton_16']</value>
      <webElementGuid>f79abf63-48a1-4c69-b20f-abe37cdc443a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
