<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_buttonPantalla_Esquemadelciclodelagua</name>
   <tag></tag>
   <elementGuidId>46b1cf43-1f59-48cb-9c7c-faa00cbff35f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pantalla_26']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f99787d5-922c-4733-8e58-c103697a95fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>xMidYMid meet</value>
      <webElementGuid>6725a8b0-6664-4e43-8000-5ebac2a3e77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4d16dec-69e7-44ae-8b34-9554138fd74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 17.5 17.5</value>
      <webElementGuid>a91b313a-9c32-4964-82a6-28cd6cad4123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buscador&quot;)/div[@class=&quot;mt-4 ng-tns-c340-18&quot;]/div[@class=&quot;expansible-jumbotron expansible-jumbotron__grey ng-tns-c340-18&quot;]/div[@class=&quot;d-flex flex-column mb-0 w-100 filter-input ng-tns-c340-18&quot;]/div[@class=&quot;d-flex mb-0 py-2 w-100 align-items-center justify-content-between ng-tns-c340-18&quot;]/mat-card-subtitle[@class=&quot;mat-card-subtitle custom-text font-weight-bold mb-0 pt-0 w-100 ng-tns-c340-18&quot;]/div[@class=&quot;d-flex pt-0 mb-2 ng-tns-c340-18&quot;]/div[@class=&quot;search-filter-input d-flex align-items-center px-1 ng-tns-c340-18 search-filter-input__typing&quot;]/mat-spinner[@class=&quot;mat-spinner mat-progress-spinner ml-2 custom-spinner mat-primary ng-tns-c340-18 mat-progress-spinner-indeterminate-animation ng-star-inserted&quot;]/svg[1]</value>
      <webElementGuid>38499f35-3fbe-418a-b051-80ab3b07fbdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pantalla_26']</value>
      <webElementGuid>179d61e6-45f9-428d-8aa5-82afe718ab1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
