<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_buttonPantalla_verciclodelagua</name>
   <tag></tag>
   <elementGuidId>0d555d53-e363-4142-b7fe-f7bb83f18dfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pantalla_37']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#material</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9c8b4c53-9d73-42e8-8069-35f39fb9b2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>material</value>
      <webElementGuid>3b7bff57-30b6-4e33-9481-bec115f3e7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c319-45</value>
      <webElementGuid>79ef6827-6a11-4c77-9f3d-dc3960ea7979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat.aulaplaneta.com/Contenido/TemplatesCPCA/html5/v1/players/F1/Principal.html?_preload_data=/Contenido/Modulos/1-2110-1-27734/</value>
      <webElementGuid>592a739e-52d9-4fce-9f8b-b14f4e2794ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;material&quot;)</value>
      <webElementGuid>e1b8593a-d476-4da8-83d2-96c1a6c96b49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pantalla_37']</value>
      <webElementGuid>e248c0a3-bc4e-43ba-9eef-18120c509598</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
