<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Presentacin multimedia_material</name>
   <tag></tag>
   <elementGuidId>e0313bbf-1459-4377-9256-3a344dbefca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='material']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#material</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e37c4772-3582-4c5f-b544-f8e5b5cf1ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>material</value>
      <webElementGuid>6d4a2e6d-d7c2-40cd-9957-315ec60899fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c336-57</value>
      <webElementGuid>06c9447b-e02f-452b-bd49-9d90f8eaf81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat.aulaplaneta.com/Contenido/TemplatesCPCA/html5/v1/players/F1/Principal.html?_preload_data=/Contenido/Modulos/1-2110-1-27734/</value>
      <webElementGuid>79e9392b-1eeb-4496-917d-c2bebe933929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;material&quot;)</value>
      <webElementGuid>812aadbd-0932-4e84-b5d6-c4843ada170d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='material']</value>
      <webElementGuid>9f8379db-59ac-49df-a41f-5d1458372539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ifrcontainer']/iframe</value>
      <webElementGuid>e4586e13-c784-46f4-8721-27b66588fcd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2c8a0b48-74dd-45e0-84b6-ba6b7049f284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'material' and @src = 'https://uat.aulaplaneta.com/Contenido/TemplatesCPCA/html5/v1/players/F1/Principal.html?_preload_data=/Contenido/Modulos/1-2110-1-27734/']</value>
      <webElementGuid>1e6009f8-0e66-4d9c-bb28-540f0e93dcbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
