<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_30_Esquema</name>
   <tag></tag>
   <elementGuidId>50e15290-ac0e-4533-8d74-40ddc2738b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;image_30&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#roundbutton_16 > #textButtonContainer > tbody > tr > td > #realContent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3785c084-2119-46e6-a7c2-b7c504f1658a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>realContent</value>
      <webElementGuid>b5ffbe1e-0cb5-41e4-8349-b4c4a00c7981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Esquema del ciclo del agua</value>
      <webElementGuid>7495db35-59b8-4c4b-b93d-006387fb8156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roundbutton_16&quot;)/table[@id=&quot;textButtonContainer&quot;]/tbody[1]/tr[1]/td[1]/div[@id=&quot;realContent&quot;]</value>
      <webElementGuid>fea5c266-d6c6-455d-a025-cd4323747f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mis materias - aulaPlaneta/div_buttonPantalla_Esquemadelciclodelagua</value>
      <webElementGuid>593d1a25-e5d9-4bb3-bc14-9c07813e89e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=&quot;image_30&quot;]</value>
      <webElementGuid>496af2d2-53be-4a5b-895c-4b75fb8193e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
