<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_30_VerCicloAgua_filtracion</name>
   <tag></tag>
   <elementGuidId>9934a955-ac94-493d-9df4-95088b237232</elementGuidId>
   <imagePath>../../Desktop/evaporacion.gif</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../Desktop/evaporacion.gif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div[2]/div[1]/div[10]/div[1]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#roundbutton_16 > #textButtonContainer > tbody > tr > td > #realContent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'realContent' and (text() = 'Esquema del ciclo del agua' or . = 'Esquema del ciclo del agua')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ea2e993-0a86-4a45-a2d2-3b75f14bc9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>realContent</value>
      <webElementGuid>e329347e-a98f-402e-b19f-e132ad481594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Esquema del ciclo del agua</value>
      <webElementGuid>dba18356-4fb1-41a8-bd2f-b4efa4ae8652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roundbutton_16&quot;)/table[@id=&quot;textButtonContainer&quot;]/tbody[1]/tr[1]/td[1]/div[@id=&quot;realContent&quot;]</value>
      <webElementGuid>bc05d25d-2e61-4ed0-88ee-5471a95c100e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/div[2]/div[1]/div[10]/div[1]/img</value>
      <webElementGuid>19883bfa-ca3f-43b5-ac01-8d8d44a6ced9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
