<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_30_VerCicloAgua_evaporacion</name>
   <tag></tag>
   <elementGuidId>50e15290-ac0e-4533-8d74-40ddc2738b5b</elementGuidId>
   <imagePath>../../Desktop/evaporacion.gif</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../Desktop/evaporacion.gif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div[2]/div[1]/div[7]/div[1]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#roundbutton_16 > #textButtonContainer > tbody > tr > td > #realContent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'realContent' and (text() = 'Esquema del ciclo del agua' or . = 'Esquema del ciclo del agua')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52806441-45f5-4ed1-bf8e-40b20e3ec1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>realContent</value>
      <webElementGuid>23842f7a-a944-4452-a844-341b2d1a6dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Esquema del ciclo del agua</value>
      <webElementGuid>32269cb8-e70f-43b0-9881-a1bee58aaa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roundbutton_16&quot;)/table[@id=&quot;textButtonContainer&quot;]/tbody[1]/tr[1]/td[1]/div[@id=&quot;realContent&quot;]</value>
      <webElementGuid>8e8d3ff6-afdc-47c8-8e11-0cf158b56ee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/div[2]/div[1]/div[7]/div[1]/img</value>
      <webElementGuid>3fd08768-3c87-4a90-bff4-35e8fb36097e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
