<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_30_VerCicloAgua_precipitacion</name>
   <tag></tag>
   <elementGuidId>e914aa6f-d55c-4898-bfdc-26b7d616ba6f</elementGuidId>
   <imagePath>../../Desktop/evaporacion.gif</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../Desktop/evaporacion.gif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div[2]/div[1]/div[9]/div[1]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#roundbutton_16 > #textButtonContainer > tbody > tr > td > #realContent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'realContent' and (text() = 'Esquema del ciclo del agua' or . = 'Esquema del ciclo del agua')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79bc03ef-dc35-443d-b7a7-4ae49856ccec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>realContent</value>
      <webElementGuid>84e59c79-3b90-44bc-ad5b-566f32ff4f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Esquema del ciclo del agua</value>
      <webElementGuid>446fea67-d886-43b1-aab7-e6128e7cc97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roundbutton_16&quot;)/table[@id=&quot;textButtonContainer&quot;]/tbody[1]/tr[1]/td[1]/div[@id=&quot;realContent&quot;]</value>
      <webElementGuid>6d5621d0-8974-4dea-8a5b-090e125b1866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/div[2]/div[1]/div[9]/div[1]/img</value>
      <webElementGuid>9323f506-29b5-4060-a2c5-353144c38f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
